[workspace]
members = [
    "bench",
    "core",
    "examples/kni",
    "examples/nat64",
    "examples/ping4d",
    "examples/pktdump",
    "examples/skeleton",
    "examples/syn-flood",
    "ffi",
    "macros"
]
