[package]
name = "capsule-bench"
version = "0.1.0"
authors = ["Capsule Developers <occam_engineering@comcast.com>"]
license = "Apache-2.0"
keywords = []
publish = false
edition = "2018"
build = "build.rs"
description = "Benchmarks for Capsule"
categories = []

[dev-dependencies]
capsule = { path = "../core", features = ["testils"] }
criterion = "0.3"
proptest = "0.9"

[[bench]]
name = "packets"
harness = false

[[bench]]
name = "combinators"
harness = false

[[bench]]
name = "mbuf"
harness = false
